/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ssehub_kernel_haven_cnf_CryptoMiniSatSolver */

#ifndef _Included_net_ssehub_kernel_haven_cnf_CryptoMiniSatSolver
#define _Included_net_ssehub_kernel_haven_cnf_CryptoMiniSatSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ssehub_kernel_haven_cnf_CryptoMiniSatSolver
 * Method:    isSatisfiableImpl
 * Signature: (IILjava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_ssehub_kernel_1haven_cnf_CryptoMiniSatSolver_isSatisfiableImpl
  (JNIEnv *, jclass, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
